export type Vehicle = {
  id: string;
  source: string;
  stock_number: string;
  make: string;
  model: string | null;
  main_type: string | null;
  sub_type: string | null;
  year: number | null;
  first_registration_date: string | null;
  mileage_km: number | null;
  fuel_type: string | null;
  engine_ccm: number | null;
  gearbox: string | null;
  body_type: string | null;
  power_kw: number | null;
  power_hp: number | null;
  co2: number | null;
  seats: number | null;
  doors: number | null;
  exterior_colour: string | null;
  upholstery: string | null;
  country_of_origin: string | null;
  country_of_registration: string | null;
  current_location_country: string | null;
  current_location_city: string | null;
  keys: number | null;
  owners: number | null;
  has_photos: boolean | null;
  manufacturer_filter: string | null;
  source_url: string | null;
  status: string;
  last_seen_at: string | null;
  first_seen_at: string | null;
  updated_at: string | null;
  auction_identifier: string | null;
  auction_type: string | null;
  auction_start_at: string | null;
  auction_end_at: string | null;
  minimum_bid: number | null;
  top_bid: number | null;
  buy_now_price: number | null;
  search_price: number | null;
  transport_eur?: number | null;
  expected_price: number | null;
  reserve_price_hidden: boolean | null;
  is_buy_now_eligible: boolean | null;
  is_instant_purchase_offer_enabled: boolean | null;
  inspection_report_path: string | null;
  service_last_mileage: number | null;
  service_last_on: string | null;
  service_appointments: string | null;
  service_book: string | null;
  technical_inspection_certificate_issue_date: string | null;
  technical_inspection_certificate_issue_mileage: number | null;
  features: Record<string, unknown> | null;
  accidents: unknown[] | null;
  videos: unknown[] | null;
  sync_hash: string | null;
  detail_synced_at: string | null;
};

export type VehicleImage = {
  id: string;
  vehicle_id: string;
  absolute_url: string;
  area: string | null;
  part: string | null;
  mime_type: string | null;
  sort_order: number;
  is_document: boolean;
  is_damage_photo: boolean;
};
